### ISSUE TITLE
Need a way to type annotate functions.

### ISSUE THREAD

**Issue by jonahwilliams** [clutchlang/clutchlang#104]
Consider the fib example:

```
fib(n) -> if n < 2 then n else fib(n - 1) + fib(n - 2)
```

Given that this is a top level declaration and has no type annotations, how would we determine the type of the function is `(Number) -> Number`? We could attempt to infer based on the body, but since the function itself is recursive, I believe we would need to make some leaps based on what types have `-`, `<`, and `+` defined.

This may not work forever, consider a more general method call:

```
fn(x) -> x.foo() // Where should I look for the definition of foo?
```

Or how about an equality comparison?

```
fn(x, y) -> x == y // Can infer boolean as return, but what are the types of x and y?
```

We have a few different options, I don't have a strong opinion. We should leave ourselves some room to annotate the return type though.
```
// Typescript style
fib(n: number): number ->  if n < 2 then n else fib(n - 1) + fib(n - 2)

// C style
number fib(number n) ->  if n < 2 then n else fib(n - 1) + fib(n - 2)

// ML style
fib(number) -> number
fib(n)      ->  if n < 2 then n else fib(n - 1) + fib(n - 2)
```

**Comment by matanlurey** [comment]
I'm guessing based on our discussion today we are going "TypeScript"-style.

(And requiring explicit type arguments)
